### ISSUE TITLE
Widget für EIERSTÖCKE :-) ?

### ISSUE THREAD

**Issue by mcm1957** [oweitman/ioBroker.vis-2-widgets-ovarious#5]
"desc": {
      "en": "Vis-2 widget ovarious",
      "de": "**Vis-2-Widget Eierstöcke**",
      "ru": "Виджет ВИЗ-2 разный",
      "pt": "Widget Vis-2 ovário",
      "nl": "Vis-2 widget eierstok",
      "fr": "Vis-2 widget ovaire",
      "it": "Widget Vis-2 ovarico",
      "es": "Widget Vis-2 ovario",
      "pl": "Widget Vis-2 jajnik",
      "uk": "Віз-2 віджет яєчників",
      "zh-cn": "Vis-2 小部件卵巢"
    },

Please check if ovarious has been mixed up with ovaren at other places too ...

**Comment by oweitman** [comment]
Fixed in 0.1,9
